// Mocks generated by Mockito 5.4.5 from annotations
// in bigchanllger/test/credits_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bigchanllger/models/generated_video.dart' as _i6;
import 'package:bigchanllger/models/user.dart' as _i7;
import 'package:bigchanllger/models/user_config.dart' as _i5;
import 'package:bigchanllger/service/database_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> saveConfig(_i5.UserConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfig, [config]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.UserConfig?> getConfig(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, [key]),
            returnValue: _i4.Future<_i5.UserConfig?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.UserConfig?>.value(),
          )
          as _i4.Future<_i5.UserConfig?>);

  @override
  _i4.Future<int> saveGeneratedVideo(_i6.GeneratedVideo? video) =>
      (super.noSuchMethod(
            Invocation.method(#saveGeneratedVideo, [video]),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i6.GeneratedVideo>> getAllVideos() =>
      (super.noSuchMethod(
            Invocation.method(#getAllVideos, []),
            returnValue: _i4.Future<List<_i6.GeneratedVideo>>.value(
              <_i6.GeneratedVideo>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i6.GeneratedVideo>>.value(
                  <_i6.GeneratedVideo>[],
                ),
          )
          as _i4.Future<List<_i6.GeneratedVideo>>);

  @override
  _i4.Future<void> deleteVideo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVideo, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUser(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.User?> getLastLoggedInUser() =>
      (super.noSuchMethod(
            Invocation.method(#getLastLoggedInUser, []),
            returnValue: _i4.Future<_i7.User?>.value(),
            returnValueForMissingStub: _i4.Future<_i7.User?>.value(),
          )
          as _i4.Future<_i7.User?>);

  @override
  _i4.Future<void> deleteUser(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
